openapi: 3.0.2
info:
  title: Zooz of the word
  version: '1.0'
  description: |
    API to handle the information of Zoos
  contact:
    name: Sarkis Panosian
    url: 'blabla'
    email: blabla@bla.com
servers:
  - url: 'https://localhost:5000'
paths:
  /api/zoos:
    get:
      tags:
        - Zoos
      summary: Get all Zoos.
      operationId: getZoos
      description: Returned an Array of all Zoos
      responses:
          '200':
            description: OK
            content:
              application/json; charset=utf-8:
                schema:
                  $ref: '#/components/schemas/Zoos'
          '400':
            description: Bad request
            content:
              application/json; charset=utf-8:
                schema:
                  $ref: '#/components/schemas/errorModelList'
          '401':
            description: Unauthorized
            content:
              application/json; charset=utf-8:
                schema:
                  $ref: '#/components/schemas/errorModelList'
          '500':
            description: Internal Server Error
            content:
              application/json; charset=utf-8:
                schema:
                  $ref: '#/components/schemas/errorModelList'
    post:
      tags:
        - Zoos
      summary: Create a new Zoo
      operationId: postZoo
      description: Create a new Zoo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Zoo'
        required: true
      responses:
        '201':
          description: Created
          content:
            text/plain; charset=utf-8:
              schema:
                $ref: '#/components/schemas/zoo'
        '400':
          description: Bad request
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '401':
          description: Unauthorized
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '500':
          description: Internal Server Error
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
  /api/zoos/{id}:
    get:
      tags:
        - Zoos
      summary: Get a Zoo.
      operationId: getZooById
      description: Returned a Zoo with the same id
      parameters:
        - name: id
          in: path
          description: Zoo ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Zoo'
        '400':
          description: Bad request
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '401':
          description: Unauthorized
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '500':
          description: Internal Server Error
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
    put:
      security:
        - Bearer: []
      tags:
        - Zoos
      summary: Modify a Zoo
      operationId: modifyZooById
      description: Modify a Zoo with ID
      parameters:
        - name: id
          in: path
          description: Zoo ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Zoo'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Zoo'
        '400':
          description: Bad request
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '401':
          description: Unauthorized
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '500':
          description: Internal Server Error
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
    delete:
      tags:
        - Zoos
      summary: Delete a Zoo.
      operationId: deleteZooById
      description: Delete a Zoo with the same id
      parameters:
        - name: id
          in: path
          description: Zoo ID
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '400':
          description: Bad request
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '401':
          description: Unauthorized
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '404':
          description: Not Found
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
        '500':
          description: Internal Server Error
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/errorModelList'
components:
  schemas:
    Zoos:
      title: Zoos
      description: A list of Zoos
      type: array
      items:
        $ref: '#/components/schemas/Zoo'
    Zoo:
      title: Zoo
      description: Object for Zoo
      type: object
      properties:
        name:
          description: Name of the zoo
          type: string
          example: Example Name
        director:
          description: Director of the zoo
          type: string
          example: Example Director
        employers:
          description: Employers of the zoo
          type: array
          example: ["E1","E2"]
        animals:
          description: Animals of the zoo
          type: array
          example: ["A1","A2"]
      required:
        - name
        - director
        - employers
        - animals  
    errorModelList:
      title: List Error Model
      description: Common defintion for a list of errors. To be used as body in combination with the HTTP status code.
      type: object
      properties:
        errors:
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/errorModel'
    errorModel:
      title: Error Model
      description: Common defintion of an error. To be used as body in combination with the HTTP status code.
      type: object
      properties:
        code:
          type: string
        property:
          type: string
        message:
          type: string

    
    
    